import { Region, Hotspot, WeatherData, PipelineLog, RegionHourlyForecast } from '../types';
import { evaluateRegionRisk, calculateImpact, generateAlertContent } from './riskEngine';

const INITIAL_HOTSPOTS: Hotspot[] = [
  // Pantanal Sul (Corumbá)
  {
    id: 'hs-firms-01',
    latitude: -19.0089,
    longitude: -57.6534,
    satellite: 'NOAA-20 (VIIRS)',
    confidence: 94,
    frp: 86.4,
    timestamp: '14:22 UTC',
    source: 'NASA FIRMS',
    municipality: 'Corumbá',
    state: 'MS',
    biome: 'Pantanal',
  },
  {
    id: 'hs-firms-02',
    latitude: -18.892,
    longitude: -57.512,
    satellite: 'Aqua (MODIS)',
    confidence: 88,
    frp: 52.1,
    timestamp: '15:10 UTC',
    source: 'NASA FIRMS',
    municipality: 'Corumbá',
    state: 'MS',
    biome: 'Pantanal',
  },
  // Pantanal Norte (Poconé)
  {
    id: 'hs-inpe-07',
    latitude: -16.257,
    longitude: -56.623,
    satellite: 'NOAA-21 (VIIRS)',
    confidence: 93,
    frp: 78.5,
    timestamp: '14:35 UTC',
    source: 'INPE Queimadas',
    municipality: 'Poconé',
    state: 'MT',
    biome: 'Pantanal',
  },
  // Amazônia Oriental / Arco do Fogo (São Félix do Xingu)
  {
    id: 'hs-firms-09',
    latitude: -6.644,
    longitude: -51.995,
    satellite: 'NOAA-20 (VIIRS)',
    confidence: 97,
    frp: 112.3,
    timestamp: '13:58 UTC',
    source: 'NASA FIRMS',
    municipality: 'São Félix do Xingu',
    state: 'PA',
    biome: 'Amazônia',
  },
  // Chapada dos Veadeiros / Alto Paraíso (GO)
  {
    id: 'hs-firms-11',
    latitude: -14.133,
    longitude: -47.514,
    satellite: 'GOES-16',
    confidence: 89,
    frp: 62.8,
    timestamp: '16:15 UTC',
    source: 'NASA FIRMS',
    municipality: 'Alto Paraíso de Goiás',
    state: 'GO',
    biome: 'Cerrado',
  },
  // Amazônia Ocidental (Porto Velho)
  {
    id: 'hs-inpe-03',
    latitude: -8.7619,
    longitude: -63.9039,
    satellite: 'NOAA-21 (VIIRS)',
    confidence: 91,
    frp: 74.8,
    timestamp: '13:45 UTC',
    source: 'INPE Queimadas',
    municipality: 'Porto Velho',
    state: 'RO',
    biome: 'Amazônia',
  },
  // MATOPIBA (Balsas)
  {
    id: 'hs-firms-04',
    latitude: -7.532,
    longitude: -46.035,
    satellite: 'GOES-16',
    confidence: 82,
    frp: 41.5,
    timestamp: '16:02 UTC',
    source: 'NASA FIRMS',
    municipality: 'Balsas',
    state: 'MA',
    biome: 'Cerrado',
  },
  // Interior Paulista (Ribeirão Preto)
  {
    id: 'hs-inpe-05',
    latitude: -21.1767,
    longitude: -47.8108,
    satellite: 'Aqua (MODIS)',
    confidence: 76,
    frp: 28.3,
    timestamp: '15:30 UTC',
    source: 'INPE Queimadas',
    municipality: 'Ribeirão Preto',
    state: 'SP',
    biome: 'Mata Atlântica / Cerrado',
  },
];

function generateHourlyTrends(
  baseTemp: number,
  baseHum: number,
  baseRain: number,
  baseFireRisk: number,
  baseHeatRisk: number,
  baseRainRisk: number
): RegionHourlyForecast[] {
  const hours = [8, 10, 12, 14, 16, 18, 20];
  return hours.map((hour, idx) => {
    const hourFactor = Math.sin(((hour - 8) / 12) * Math.PI);
    const temp = Math.round((baseTemp - 4 + hourFactor * 5) * 10) / 10;
    const hum = Math.max(12, Math.round(baseHum + 15 - hourFactor * 22));
    const rain = Math.max(0, Math.round(baseRain + (hour >= 14 && baseRain > 0 ? (idx - 2) * 8 : 0)));

    const fireR = Math.min(100, Math.max(10, Math.round(baseFireRisk - 18 + hourFactor * 24)));
    const heatR = Math.min(100, Math.max(8, Math.round(baseHeatRisk - 15 + hourFactor * 20)));
    const rainR = Math.min(100, Math.max(5, Math.round(baseRainRisk + (hour >= 14 ? 12 : -5))));
    const overall = Math.max(fireR, heatR, rainR);

    return {
      time: `${String(hour).padStart(2, '0')}:00`,
      hour,
      temperature: temp,
      humidity: hum,
      rain,
      fireRisk: fireR,
      heatRisk: heatR,
      rainRisk: rainR,
      overallRisk: overall,
    };
  });
}

export function buildInitialRegions(): Region[] {
  const rawRegionsConfig = [
    // ==========================================
    // 27 CAPITAIS BRASILEIRAS (ESTÁVEIS E EVENTOS)
    // ==========================================
    {
      id: 'brasilia-df',
      name: 'Brasília',
      state: 'DF',
      biome: 'Cerrado',
      latitude: -15.7801,
      longitude: -47.9292,
      radiusKm: 35,
      vegetationStatus: 'seca' as const,
      population: 3055000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 29.4,
        humidity: 32,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 17,
        windDirection: 'E',
        daysWithoutRain: 14,
        heatIndex: 29.8,
        soilMoisture: 35,
        conditionText: 'Céu Aberto / Sol Entre Nuvens',
        updatedAt: 'Há 5 min',
      },
      ruralAreaRatio: 18,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'sao-paulo-sp',
      name: 'São Paulo',
      state: 'SP',
      biome: 'Mata Atlântica',
      latitude: -23.5505,
      longitude: -46.6333,
      radiusKm: 40,
      vegetationStatus: 'moderada' as const,
      population: 12396000,
      leadTimeHours: 3.5,
      weather: {
        temperature: 25.2,
        humidity: 65,
        precipitation: 5,
        precipitationForecast: 15,
        windSpeed: 14,
        windDirection: 'SE',
        daysWithoutRain: 2,
        heatIndex: 25.8,
        soilMoisture: 58,
        conditionText: 'Parcialmente Nublado',
        updatedAt: 'Há 4 min',
      },
      ruralAreaRatio: 8,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'rio-de-janeiro-rj',
      name: 'Rio de Janeiro',
      state: 'RJ',
      biome: 'Mata Atlântica',
      latitude: -22.9068,
      longitude: -43.1729,
      radiusKm: 40,
      vegetationStatus: 'moderada' as const,
      population: 6775000,
      leadTimeHours: 3.2,
      weather: {
        temperature: 34.0,
        humidity: 58,
        precipitation: 0,
        precipitationForecast: 5,
        windSpeed: 16,
        windDirection: 'S',
        daysWithoutRain: 6,
        heatIndex: 38.5,
        soilMoisture: 50,
        conditionText: 'Sol com Calor Moderado',
        updatedAt: 'Há 2 min',
      },
      ruralAreaRatio: 12,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'belo-horizonte-mg',
      name: 'Belo Horizonte',
      state: 'MG',
      biome: 'Cerrado / Mata Atlântica',
      latitude: -19.9208,
      longitude: -43.9378,
      radiusKm: 35,
      vegetationStatus: 'moderada' as const,
      population: 2530000,
      leadTimeHours: 3.8,
      weather: {
        temperature: 26.5,
        humidity: 78,
        precipitation: 45,
        precipitationForecast: 65,
        windSpeed: 19,
        windDirection: 'NW',
        daysWithoutRain: 0,
        heatIndex: 27.2,
        soilMoisture: 82,
        conditionText: 'Pancadas de Chuva',
        updatedAt: 'Há 6 min',
      },
      ruralAreaRatio: 15,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'salvador-ba',
      name: 'Salvador',
      state: 'BA',
      biome: 'Mata Atlântica',
      latitude: -12.9777,
      longitude: -38.5016,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 2900000,
      leadTimeHours: 4.2,
      weather: {
        temperature: 28.5,
        humidity: 74,
        precipitation: 12,
        precipitationForecast: 22,
        windSpeed: 21,
        windDirection: 'E',
        daysWithoutRain: 1,
        heatIndex: 31.0,
        soilMoisture: 70,
        conditionText: 'Brisa Marítima e Chuva Rápida',
        updatedAt: 'Há 8 min',
      },
      ruralAreaRatio: 10,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'fortaleza-ce',
      name: 'Fortaleza',
      state: 'CE',
      biome: 'Caatinga / Litoral',
      latitude: -3.7172,
      longitude: -38.5433,
      radiusKm: 35,
      vegetationStatus: 'moderada' as const,
      population: 2700000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 31.2,
        humidity: 62,
        precipitation: 2,
        precipitationForecast: 4,
        windSpeed: 26,
        windDirection: 'E',
        daysWithoutRain: 5,
        heatIndex: 35.1,
        soilMoisture: 48,
        conditionText: 'Ensolarado com Vento Forte',
        updatedAt: 'Há 7 min',
      },
      ruralAreaRatio: 8,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'curitiba-pr',
      name: 'Curitiba',
      state: 'PR',
      biome: 'Mata Atlântica',
      latitude: -25.4297,
      longitude: -49.2719,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 1963000,
      leadTimeHours: 4.5,
      weather: {
        temperature: 18.2,
        humidity: 82,
        precipitation: 8,
        precipitationForecast: 18,
        windSpeed: 15,
        windDirection: 'S',
        daysWithoutRain: 1,
        heatIndex: 18.2,
        soilMoisture: 78,
        conditionText: 'Ameno e Parcialmente Nublado',
        updatedAt: 'Há 10 min',
      },
      ruralAreaRatio: 12,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'porto-alegre-rs',
      name: 'Porto Alegre',
      state: 'RS',
      biome: 'Pampa / Mata Atlântica',
      latitude: -30.0346,
      longitude: -51.2177,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 1492000,
      leadTimeHours: 5.0,
      weather: {
        temperature: 21.0,
        humidity: 88,
        precipitation: 40,
        precipitationForecast: 60,
        windSpeed: 22,
        windDirection: 'SW',
        daysWithoutRain: 0,
        heatIndex: 21.0,
        soilMoisture: 91,
        conditionText: 'Chuva Contínua / Lago Guaíba',
        updatedAt: 'Há 5 min',
      },
      ruralAreaRatio: 18,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'manaus-am',
      name: 'Manaus',
      state: 'AM',
      biome: 'Amazônia',
      latitude: -3.119,
      longitude: -60.0217,
      radiusKm: 45,
      vegetationStatus: 'moderada' as const,
      population: 2255000,
      leadTimeHours: 3.6,
      weather: {
        temperature: 36.8,
        humidity: 68,
        precipitation: 15,
        precipitationForecast: 28,
        windSpeed: 12,
        windDirection: 'E',
        daysWithoutRain: 3,
        heatIndex: 44.5,
        soilMoisture: 65,
        conditionText: 'Calor Úmido e Pancadas',
        updatedAt: 'Há 12 min',
      },
      ruralAreaRatio: 30,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'belem-pa',
      name: 'Belém',
      state: 'PA',
      biome: 'Amazônia',
      latitude: -1.4558,
      longitude: -48.4902,
      radiusKm: 38,
      vegetationStatus: 'umida' as const,
      population: 1500000,
      leadTimeHours: 3.8,
      weather: {
        temperature: 32.5,
        humidity: 76,
        precipitation: 25,
        precipitationForecast: 40,
        windSpeed: 14,
        windDirection: 'NE',
        daysWithoutRain: 0,
        heatIndex: 39.2,
        soilMoisture: 80,
        conditionText: 'Chuva da Tarde / Maré Fluvial',
        updatedAt: 'Há 9 min',
      },
      ruralAreaRatio: 20,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'recife-pe',
      name: 'Recife',
      state: 'PE',
      biome: 'Mata Atlântica / Litoral',
      latitude: -8.0476,
      longitude: -34.877,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 1661000,
      leadTimeHours: 4.1,
      weather: {
        temperature: 29.0,
        humidity: 79,
        precipitation: 30,
        precipitationForecast: 55,
        windSpeed: 18,
        windDirection: 'SE',
        daysWithoutRain: 0,
        heatIndex: 33.4,
        soilMoisture: 85,
        conditionText: 'Chuva Moderada Litorânea',
        updatedAt: 'Há 8 min',
      },
      ruralAreaRatio: 12,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'goiania-go',
      name: 'Goiânia',
      state: 'GO',
      biome: 'Cerrado',
      latitude: -16.6869,
      longitude: -49.2648,
      radiusKm: 38,
      vegetationStatus: 'seca' as const,
      population: 1555000,
      leadTimeHours: 3.7,
      weather: {
        temperature: 34.5,
        humidity: 28,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 18,
        windDirection: 'E',
        daysWithoutRain: 18,
        heatIndex: 36.2,
        soilMoisture: 28,
        conditionText: 'Tempo Seco e Ensolarado',
        updatedAt: 'Há 11 min',
      },
      ruralAreaRatio: 22,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'cuiaba-mt',
      name: 'Cuiabá',
      state: 'MT',
      biome: 'Cerrado / Pantanal',
      latitude: -15.6014,
      longitude: -56.0979,
      radiusKm: 50,
      vegetationStatus: 'seca' as const,
      population: 650000,
      leadTimeHours: 3.8,
      weather: {
        temperature: 41.8,
        humidity: 17,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 18,
        windDirection: 'N',
        daysWithoutRain: 25,
        heatIndex: 46.5,
        soilMoisture: 20,
        conditionText: 'Onda de Calor Intensa',
        updatedAt: 'Há 6 min',
      },
      ruralAreaRatio: 25,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'campo-grande-ms',
      name: 'Campo Grande',
      state: 'MS',
      biome: 'Cerrado',
      latitude: -20.4697,
      longitude: -54.6201,
      radiusKm: 40,
      vegetationStatus: 'seca' as const,
      population: 916000,
      leadTimeHours: 3.9,
      weather: {
        temperature: 35.0,
        humidity: 25,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 24,
        windDirection: 'NE',
        daysWithoutRain: 16,
        heatIndex: 37.0,
        soilMoisture: 25,
        conditionText: 'Ensolarado e Ventoso',
        updatedAt: 'Há 13 min',
      },
      ruralAreaRatio: 28,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'palmas-to',
      name: 'Palmas',
      state: 'TO',
      biome: 'Cerrado',
      latitude: -10.184,
      longitude: -48.333,
      radiusKm: 40,
      vegetationStatus: 'seca' as const,
      population: 313000,
      leadTimeHours: 3.7,
      weather: {
        temperature: 40.0,
        humidity: 19,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 16,
        windDirection: 'SE',
        daysWithoutRain: 28,
        heatIndex: 43.8,
        soilMoisture: 17,
        conditionText: 'Calor Extremo / Baixa Umidade',
        updatedAt: 'Há 11 min',
      },
      ruralAreaRatio: 30,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'teresina-pi',
      name: 'Teresina',
      state: 'PI',
      biome: 'Cerrado / Caatinga',
      latitude: -5.0919,
      longitude: -42.8034,
      radiusKm: 45,
      vegetationStatus: 'seca' as const,
      population: 868000,
      leadTimeHours: 4.1,
      weather: {
        temperature: 40.5,
        humidity: 21,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 15,
        windDirection: 'E',
        daysWithoutRain: 32,
        heatIndex: 45.2,
        soilMoisture: 18,
        conditionText: 'Insolação Forte (B-R-O Bró)',
        updatedAt: 'Há 14 min',
      },
      ruralAreaRatio: 20,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'natal-rn',
      name: 'Natal',
      state: 'RN',
      biome: 'Caatinga / Litoral',
      latitude: -5.7945,
      longitude: -35.211,
      radiusKm: 32,
      vegetationStatus: 'moderada' as const,
      population: 890000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 29.8,
        humidity: 70,
        precipitation: 4,
        precipitationForecast: 10,
        windSpeed: 25,
        windDirection: 'SE',
        daysWithoutRain: 3,
        heatIndex: 33.0,
        soilMoisture: 60,
        conditionText: 'Céu Claro com Ventos Alísios',
        updatedAt: 'Há 7 min',
      },
      ruralAreaRatio: 10,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'joao-pessoa-pb',
      name: 'João Pessoa',
      state: 'PB',
      biome: 'Mata Atlântica / Litoral',
      latitude: -7.1195,
      longitude: -34.845,
      radiusKm: 32,
      vegetationStatus: 'moderada' as const,
      population: 817000,
      leadTimeHours: 4.2,
      weather: {
        temperature: 29.2,
        humidity: 72,
        precipitation: 6,
        precipitationForecast: 12,
        windSpeed: 23,
        windDirection: 'SE',
        daysWithoutRain: 2,
        heatIndex: 32.5,
        soilMoisture: 65,
        conditionText: 'Brisa Suave e Sol',
        updatedAt: 'Há 9 min',
      },
      ruralAreaRatio: 12,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'maceio-al',
      name: 'Maceió',
      state: 'AL',
      biome: 'Mata Atlântica / Litoral',
      latitude: -9.6658,
      longitude: -35.735,
      radiusKm: 32,
      vegetationStatus: 'moderada' as const,
      population: 1025000,
      leadTimeHours: 3.9,
      weather: {
        temperature: 28.8,
        humidity: 75,
        precipitation: 14,
        precipitationForecast: 25,
        windSpeed: 19,
        windDirection: 'E',
        daysWithoutRain: 1,
        heatIndex: 31.8,
        soilMoisture: 72,
        conditionText: 'Sol entre Nuvens',
        updatedAt: 'Há 8 min',
      },
      ruralAreaRatio: 14,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'aracaju-se',
      name: 'Aracaju',
      state: 'SE',
      biome: 'Mata Atlântica / Litoral',
      latitude: -10.9472,
      longitude: -37.0731,
      radiusKm: 30,
      vegetationStatus: 'moderada' as const,
      population: 664000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 28.5,
        humidity: 73,
        precipitation: 8,
        precipitationForecast: 15,
        windSpeed: 20,
        windDirection: 'E',
        daysWithoutRain: 2,
        heatIndex: 31.2,
        soilMoisture: 68,
        conditionText: 'Ensolarado e Estável',
        updatedAt: 'Há 10 min',
      },
      ruralAreaRatio: 10,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'sao-luis-ma',
      name: 'São Luís',
      state: 'MA',
      biome: 'Amazônia / Cerrado',
      latitude: -2.5307,
      longitude: -44.3068,
      radiusKm: 35,
      vegetationStatus: 'moderada' as const,
      population: 1108000,
      leadTimeHours: 4.1,
      weather: {
        temperature: 31.5,
        humidity: 68,
        precipitation: 10,
        precipitationForecast: 20,
        windSpeed: 22,
        windDirection: 'NE',
        daysWithoutRain: 3,
        heatIndex: 36.4,
        soilMoisture: 62,
        conditionText: 'Sol com Pancadas Tardias',
        updatedAt: 'Há 11 min',
      },
      ruralAreaRatio: 18,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'florianopolis-sc',
      name: 'Florianópolis',
      state: 'SC',
      biome: 'Mata Atlântica',
      latitude: -27.5954,
      longitude: -48.548,
      radiusKm: 32,
      vegetationStatus: 'umida' as const,
      population: 508000,
      leadTimeHours: 4.5,
      weather: {
        temperature: 21.5,
        humidity: 84,
        precipitation: 18,
        precipitationForecast: 30,
        windSpeed: 24,
        windDirection: 'NE',
        daysWithoutRain: 1,
        heatIndex: 21.8,
        soilMoisture: 80,
        conditionText: 'Nublado com Vento Marítimo',
        updatedAt: 'Há 6 min',
      },
      ruralAreaRatio: 15,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'vitoria-es',
      name: 'Vitória',
      state: 'ES',
      biome: 'Mata Atlântica',
      latitude: -20.3155,
      longitude: -40.3128,
      radiusKm: 30,
      vegetationStatus: 'moderada' as const,
      population: 365000,
      leadTimeHours: 4.2,
      weather: {
        temperature: 28.0,
        humidity: 71,
        precipitation: 5,
        precipitationForecast: 12,
        windSpeed: 18,
        windDirection: 'NE',
        daysWithoutRain: 3,
        heatIndex: 30.5,
        soilMoisture: 64,
        conditionText: 'Ensolarado com Brisa',
        updatedAt: 'Há 8 min',
      },
      ruralAreaRatio: 8,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'porto-velho-ro',
      name: 'Porto Velho',
      state: 'RO',
      biome: 'Amazônia',
      latitude: -8.7619,
      longitude: -63.9039,
      radiusKm: 60,
      vegetationStatus: 'seca' as const,
      population: 539000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 38.0,
        humidity: 30,
        precipitation: 0,
        precipitationForecast: 2,
        windSpeed: 21,
        windDirection: 'E',
        daysWithoutRain: 15,
        heatIndex: 42.8,
        soilMoisture: 32,
        conditionText: 'Tempo Seco e Fumaça',
        updatedAt: 'Há 15 min',
      },
      ruralAreaRatio: 55,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'periferia' as const,
    },
    {
      id: 'rio-branco-ac',
      name: 'Rio Branco',
      state: 'AC',
      biome: 'Amazônia',
      latitude: -9.9753,
      longitude: -67.8249,
      radiusKm: 38,
      vegetationStatus: 'seca' as const,
      population: 413000,
      leadTimeHours: 4.3,
      weather: {
        temperature: 36.5,
        humidity: 42,
        precipitation: 1,
        precipitationForecast: 5,
        windSpeed: 14,
        windDirection: 'NW',
        daysWithoutRain: 9,
        heatIndex: 41.0,
        soilMoisture: 45,
        conditionText: 'Seco e Ensolarado',
        updatedAt: 'Há 14 min',
      },
      ruralAreaRatio: 35,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'macapa-ap',
      name: 'Macapá',
      state: 'AP',
      biome: 'Amazônia',
      latitude: 0.0389,
      longitude: -51.0664,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 522000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 32.0,
        humidity: 78,
        precipitation: 20,
        precipitationForecast: 35,
        windSpeed: 17,
        windDirection: 'E',
        daysWithoutRain: 1,
        heatIndex: 38.0,
        soilMoisture: 82,
        conditionText: 'Linha do Equador / Pancadas',
        updatedAt: 'Há 10 min',
      },
      ruralAreaRatio: 25,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'boa-vista-rr',
      name: 'Boa Vista',
      state: 'RR',
      biome: 'Amazônia / Savana',
      latitude: 2.8235,
      longitude: -60.6758,
      radiusKm: 40,
      vegetationStatus: 'seca' as const,
      population: 436000,
      leadTimeHours: 4.2,
      weather: {
        temperature: 37.0,
        humidity: 38,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 19,
        windDirection: 'NE',
        daysWithoutRain: 18,
        heatIndex: 41.5,
        soilMoisture: 30,
        conditionText: 'Calor e Savana Roraimense',
        updatedAt: 'Há 12 min',
      },
      ruralAreaRatio: 35,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'centro urbano' as const,
    },

    // ==========================================
    // GRANDES POLOS REGIONAIS E ÁREAS DE MONITORAMENTO
    // ==========================================
    {
      id: 'corumba-ms',
      name: 'Corumbá (Pantanal Sul)',
      state: 'MS',
      biome: 'Pantanal',
      latitude: -19.0089,
      longitude: -57.6534,
      radiusKm: 65,
      vegetationStatus: 'muito seca' as const,
      population: 112000,
      leadTimeHours: 4.5,
      weather: {
        temperature: 39.5,
        humidity: 19,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 28,
        windDirection: 'NE',
        daysWithoutRain: 21,
        heatIndex: 43.1,
        soilMoisture: 16,
        conditionText: 'Estiagem Extrema e Foco Ativo',
        updatedAt: 'Há 5 min',
      },
      ruralAreaRatio: 75,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'periferia' as const,
    },
    {
      id: 'pocone-mt',
      name: 'Poconé (Pantanal Norte)',
      state: 'MT',
      biome: 'Pantanal',
      latitude: -16.257,
      longitude: -56.623,
      radiusKm: 60,
      vegetationStatus: 'muito seca' as const,
      population: 33000,
      leadTimeHours: 5.0,
      weather: {
        temperature: 40.2,
        humidity: 18,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 26,
        windDirection: 'N',
        daysWithoutRain: 24,
        heatIndex: 44.0,
        soilMoisture: 14,
        conditionText: 'Biomassa Seca / Risco Crítico',
        updatedAt: 'Há 10 min',
      },
      ruralAreaRatio: 82,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'isolado' as const,
    },
    {
      id: 'sao-felix-xingu-pa',
      name: 'São Félix do Xingu',
      state: 'PA',
      biome: 'Amazônia',
      latitude: -6.644,
      longitude: -51.995,
      radiusKm: 75,
      vegetationStatus: 'muito seca' as const,
      population: 135000,
      leadTimeHours: 4.2,
      weather: {
        temperature: 38.8,
        humidity: 26,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 24,
        windDirection: 'SE',
        daysWithoutRain: 19,
        heatIndex: 42.5,
        soilMoisture: 22,
        conditionText: 'Arco do Fogo / Foco Satélite',
        updatedAt: 'Há 8 min',
      },
      ruralAreaRatio: 88,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'isolado' as const,
    },
    {
      id: 'alto-paraiso-go',
      name: 'Chapada dos Veadeiros',
      state: 'GO',
      biome: 'Cerrado',
      latitude: -14.133,
      longitude: -47.514,
      radiusKm: 45,
      vegetationStatus: 'muito seca' as const,
      population: 18000,
      leadTimeHours: 3.9,
      weather: {
        temperature: 37.2,
        humidity: 20,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 27,
        windDirection: 'E',
        daysWithoutRain: 26,
        heatIndex: 39.5,
        soilMoisture: 15,
        conditionText: 'Vento Forte em Altitude',
        updatedAt: 'Há 12 min',
      },
      ruralAreaRatio: 85,
      proximityToRivers: 'moderada' as const,
      proximityToResidences: 'isolado' as const,
    },
    {
      id: 'petropolis-rj',
      name: 'Petrópolis (Região Serrana)',
      state: 'RJ',
      biome: 'Mata Atlântica',
      latitude: -22.505,
      longitude: -43.1789,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 306000,
      leadTimeHours: 5.2,
      weather: {
        temperature: 21.8,
        humidity: 92,
        precipitation: 75,
        precipitationForecast: 95,
        windSpeed: 20,
        windDirection: 'SE',
        daysWithoutRain: 0,
        heatIndex: 22.5,
        soilMoisture: 96,
        conditionText: 'Chuva Torrencial em Encostas',
        updatedAt: 'Há 3 min',
      },
      ruralAreaRatio: 30,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'vale-taquari-rs',
      name: 'Vale do Taquari (Lajeado)',
      state: 'RS',
      biome: 'Mata Atlântica / Pampa',
      latitude: -29.4667,
      longitude: -51.9667,
      radiusKm: 40,
      vegetationStatus: 'umida' as const,
      population: 240000,
      leadTimeHours: 6.0,
      weather: {
        temperature: 19.5,
        humidity: 95,
        precipitation: 88,
        precipitationForecast: 120,
        windSpeed: 24,
        windDirection: 'S',
        daysWithoutRain: 0,
        heatIndex: 19.5,
        soilMoisture: 98,
        conditionText: 'Cheia Iminente de Rio',
        updatedAt: 'Há 2 min',
      },
      ruralAreaRatio: 45,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'sao-sebastiao-sp',
      name: 'São Sebastião (Litoral Norte)',
      state: 'SP',
      biome: 'Mata Atlântica',
      latitude: -23.76,
      longitude: -45.409,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 91000,
      leadTimeHours: 4.8,
      weather: {
        temperature: 23.0,
        humidity: 94,
        precipitation: 90,
        precipitationForecast: 105,
        windSpeed: 28,
        windDirection: 'SE',
        daysWithoutRain: 0,
        heatIndex: 24.2,
        soilMoisture: 95,
        conditionText: 'Alerta de Deslizamento',
        updatedAt: 'Há 4 min',
      },
      ruralAreaRatio: 35,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'periferia' as const,
    },
    {
      id: 'blumenau-sc',
      name: 'Blumenau (Vale do Itajaí)',
      state: 'SC',
      biome: 'Mata Atlântica',
      latitude: -26.919,
      longitude: -49.066,
      radiusKm: 38,
      vegetationStatus: 'umida' as const,
      population: 366000,
      leadTimeHours: 5.5,
      weather: {
        temperature: 20.8,
        humidity: 91,
        precipitation: 62,
        precipitationForecast: 85,
        windSpeed: 19,
        windDirection: 'E',
        daysWithoutRain: 0,
        heatIndex: 21.0,
        soilMoisture: 93,
        conditionText: 'Alagamento em Calha de Rio',
        updatedAt: 'Há 7 min',
      },
      ruralAreaRatio: 25,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'campinas-sp',
      name: 'Campinas',
      state: 'SP',
      biome: 'Mata Atlântica',
      latitude: -22.9056,
      longitude: -47.0608,
      radiusKm: 35,
      vegetationStatus: 'moderada' as const,
      population: 1213000,
      leadTimeHours: 3.8,
      weather: {
        temperature: 29.0,
        humidity: 52,
        precipitation: 0,
        precipitationForecast: 8,
        windSpeed: 18,
        windDirection: 'SE',
        daysWithoutRain: 4,
        heatIndex: 30.5,
        soilMoisture: 55,
        conditionText: 'Parcialmente Ensolarado',
        updatedAt: 'Há 8 min',
      },
      ruralAreaRatio: 15,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'londrina-pr',
      name: 'Londrina',
      state: 'PR',
      biome: 'Mata Atlântica',
      latitude: -23.3103,
      longitude: -51.1628,
      radiusKm: 35,
      vegetationStatus: 'moderada' as const,
      population: 580000,
      leadTimeHours: 4.0,
      weather: {
        temperature: 26.0,
        humidity: 60,
        precipitation: 2,
        precipitationForecast: 10,
        windSpeed: 14,
        windDirection: 'S',
        daysWithoutRain: 3,
        heatIndex: 26.5,
        soilMoisture: 65,
        conditionText: 'Clima Agradável e Aberto',
        updatedAt: 'Há 12 min',
      },
      ruralAreaRatio: 25,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'santarem-pa',
      name: 'Santarém (Tapajós)',
      state: 'PA',
      biome: 'Amazônia',
      latitude: -2.4431,
      longitude: -54.7083,
      radiusKm: 45,
      vegetationStatus: 'moderada' as const,
      population: 308000,
      leadTimeHours: 4.1,
      weather: {
        temperature: 33.5,
        humidity: 70,
        precipitation: 10,
        precipitationForecast: 25,
        windSpeed: 15,
        windDirection: 'E',
        daysWithoutRain: 2,
        heatIndex: 39.0,
        soilMoisture: 70,
        conditionText: 'Calor e Encontro dos Rios',
        updatedAt: 'Há 14 min',
      },
      ruralAreaRatio: 40,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'foz-do-iguacu-pr',
      name: 'Foz do Iguaçu',
      state: 'PR',
      biome: 'Mata Atlântica',
      latitude: -25.5478,
      longitude: -54.5882,
      radiusKm: 35,
      vegetationStatus: 'umida' as const,
      population: 285000,
      leadTimeHours: 4.2,
      weather: {
        temperature: 24.5,
        humidity: 72,
        precipitation: 15,
        precipitationForecast: 30,
        windSpeed: 16,
        windDirection: 'SE',
        daysWithoutRain: 1,
        heatIndex: 25.2,
        soilMoisture: 75,
        conditionText: 'Chuva Leve nas Cataratas',
        updatedAt: 'Há 11 min',
      },
      ruralAreaRatio: 20,
      proximityToRivers: 'critica' as const,
      proximityToResidences: 'centro urbano' as const,
    },
    {
      id: 'uberlandia-mg',
      name: 'Uberlândia (Triângulo)',
      state: 'MG',
      biome: 'Cerrado',
      latitude: -18.9186,
      longitude: -48.2772,
      radiusKm: 35,
      vegetationStatus: 'seca' as const,
      population: 713000,
      leadTimeHours: 3.8,
      weather: {
        temperature: 31.0,
        humidity: 35,
        precipitation: 0,
        precipitationForecast: 0,
        windSpeed: 16,
        windDirection: 'E',
        daysWithoutRain: 12,
        heatIndex: 32.2,
        soilMoisture: 38,
        conditionText: 'Ensolarado e Seco',
        updatedAt: 'Há 15 min',
      },
      ruralAreaRatio: 24,
      proximityToRivers: 'distante' as const,
      proximityToResidences: 'centro urbano' as const,
    },
  ];

  return rawRegionsConfig.map((cfg) => {
    const matchedHotspots = INITIAL_HOTSPOTS.filter(
      (h) => Math.abs(h.latitude - cfg.latitude) < 1.3 && Math.abs(h.longitude - cfg.longitude) < 1.3
    );

    const risk = evaluateRegionRisk(cfg.weather, matchedHotspots, cfg.vegetationStatus, cfg.proximityToRivers);
    const impact = calculateImpact(
      risk,
      cfg.population,
      cfg.ruralAreaRatio,
      cfg.proximityToRivers,
      cfg.proximityToResidences
    );
    const activeAlert = generateAlertContent(
      cfg.name,
      cfg.state,
      risk,
      cfg.weather,
      impact,
      matchedHotspots,
      cfg.leadTimeHours
    );

    const hourlyTrends = generateHourlyTrends(
      cfg.weather.temperature,
      cfg.weather.humidity,
      cfg.weather.precipitationForecast,
      risk.fireRisk,
      risk.heatRisk,
      risk.rainRisk
    );

    return {
      id: cfg.id,
      name: cfg.name,
      state: cfg.state,
      biome: cfg.biome,
      latitude: cfg.latitude,
      longitude: cfg.longitude,
      radiusKm: cfg.radiusKm,
      vegetationStatus: cfg.vegetationStatus,
      population: cfg.population,
      weather: cfg.weather,
      hotspots: matchedHotspots,
      risk,
      impact,
      hourlyTrends,
      leadTimeHours: cfg.leadTimeHours,
      activeAlert,
    };
  });
}
